language: r
cache: packages


r_packages:
  - drat
  
matrix:
  include:
    - os: linux
      r: release
      env:
        - R_CODECOV=true
    - os: linux
      r: devel
    - os: linux
      r: oldrel
    - os: osx
      osx_image: xcode8.3

warnings_are_errors: true

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - if [[ "${R_CODECOV}" ]]; then Rscript -e 'covr::codecov(line_exclusions = list("R/zzz.R", "R/random_flows.R"))'; fi
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash drat.sh
